import 'package:flutter/material.dart';

final ValueNotifier<String> languageNotifier = ValueNotifier<String>('tr');

final Map<String, Map<String, String>> _translations = {
  'appTitle': {'tr': 'Mesaimatik', 'ur': 'Mesaimatik', 'ne': 'Mesaimatik', 'en': 'Mesaimatik'},
  'today': {'tr': 'Bugün', 'ur': 'آج', 'ne': 'आज', 'en': 'Today'},
  'legendOvertime': {'tr': 'Mesai', 'ur': 'اضافی کام', 'ne': 'ओभरटाइम', 'en': 'Overtime'},
  'legendLateAbsent': {'tr': 'Geç/gitmedi', 'ur': 'تاخیر/غیر حاضر', 'ne': 'ढिलो/अनुपस्थित', 'en': 'Late/absent'},
  'legendLeave': {'tr': 'İzin', 'ur': 'چھٹی', 'ne': 'बिदा', 'en': 'Leave'},
  'legendCompOff': {'tr': 'Telafi', 'ur': 'تلافی', 'ne': 'क्षतिपूर्ति', 'en': 'Comp-off'},
  'normallyNetSalaryShort': {'tr': 'Normalde net maaş', 'ur': 'عام طور پر خالص تنخواہ', 'ne': 'सामान्यतया खुद तलब', 'en': 'Normally net salary'},
  'daysNetSalaryShort': {'tr': 'günlük net maaş', 'ur': 'دن کی خالص تنخواہ', 'ne': 'दिनको खुद तलब', 'en': 'days net salary'},
  'overtimeExtraShort': {'tr': 'Fazla mesai ücreti', 'ur': 'اضافی وقت کی اجرت', 'ne': 'ओभरटाइम ज्याला', 'en': 'Overtime pay'},
  'dayStatusLabel': {'tr': 'Gün durumu', 'ur': 'دن کی حالت', 'ne': 'दिनको स्थिति', 'en': 'Day status'},
  'extraInfoLabel': {'tr': 'Ek bilgiler', 'ur': 'اضافی معلومات', 'ne': 'थप जानकारी', 'en': 'Additional info'},
  'serviceDurationLabel': {'tr': 'Hizmet süreniz', 'ur': 'ملازمت کی مدت', 'ne': 'सेवा अवधि', 'en': 'Length of service'},
  'sinceWorkingLabel': {'tr': "tarihinden beri çalışıyorsunuz", 'ur': 'سے کام کر رہے ہیں', 'ne': 'देखि काम गर्दै हुनुहुन्छ', 'en': "you've been working since"},
  'annualLeaveSectionLabel': {'tr': 'Yıllık izin', 'ur': 'سالانہ چھٹی', 'ne': 'वार्षिक बिदा', 'en': 'Annual leave'},
  'autoCalculatedLeave': {'tr': 'Hizmet sürenize göre otomatik hesaplandı', 'ur': 'ملازمت کی مدت کے مطابق خودکار حساب', 'ne': 'सेवा अवधि अनुसार स्वचालित गणना गरियो', 'en': 'Automatically calculated from your length of service'},
  'manualLeaveToggle': {'tr': 'Kendim gireceğim', 'ur': 'میں خود درج کروں گا', 'ne': 'म आफैं प्रविष्ट गर्नेछु', 'en': "I'll enter it myself"},
  'legalLeaveTitle': {'tr': 'Kanuni yıllık izin süreleri', 'ur': 'قانونی سالانہ چھٹی کی مدت', 'ne': 'कानुनी वार्षिक बिदा अवधि', 'en': 'Legal annual leave periods'},
  'legalLeaveTier1': {'tr': '1 - 5 yıl arası', 'ur': '1 - 5 سال کے درمیان', 'ne': '१ - ५ वर्ष बीच', 'en': '1 - 5 years'},
  'legalLeaveTier2': {'tr': '5 - 15 yıl arası', 'ur': '5 - 15 سال کے درمیان', 'ne': '५ - १५ वर्ष बीच', 'en': '5 - 15 years'},
  'legalLeaveTier3': {'tr': '15 yıl ve üzeri', 'ur': '15 سال یا اس سے زیادہ', 'ne': '१५ वर्ष र माथि', 'en': '15 years and above'},
  'themeSystemSubtitle': {'tr': 'Otomatik geçiş yapar', 'ur': 'خودکار تبدیل ہوتا ہے', 'ne': 'स्वचालित रूपमा परिवर्तन हुन्छ', 'en': 'Switches automatically'},
  'pdfIntroTitle': {'tr': 'Aylık raporunuzu oluşturun', 'ur': 'اپنی ماہانہ رپورٹ بنائیں', 'ne': 'तपाईंको मासिक रिपोर्ट बनाउनुहोस्', 'en': 'Create your monthly report'},
  'annualLeaveRightShort': {'tr': 'Hak', 'ur': 'حق', 'ne': 'अधिकार', 'en': 'Entitled'},
  'usedDaysShort': {'tr': 'Kullanılan', 'ur': 'استعمال شدہ', 'ne': 'प्रयोग गरिएको', 'en': 'Used'},
  'remainingDaysShort': {'tr': 'Kalan', 'ur': 'باقی', 'ne': 'बाँकी', 'en': 'Remaining'},
  'greetingMorning': {'tr': 'Günaydın', 'ur': 'صبح بخیر', 'ne': 'शुभ प्रभात', 'en': 'Good morning'},
  'greetingDay': {'tr': 'İyi günler', 'ur': 'دن اچھا گزرے', 'ne': 'शुभ दिन', 'en': 'Good day'},
  'greetingEvening': {'tr': 'İyi akşamlar', 'ur': 'شام بخیر', 'ne': 'शुभ साँझ', 'en': 'Good evening'},
  'greetingNight': {'tr': 'İyi geceler', 'ur': 'شب بخیر', 'ne': 'शुभ रात्री', 'en': 'Good night'},
  'overtimeDaysLabel': {'tr': 'Mesai günü', 'ur': 'اضافی کام کے دن', 'ne': 'ओभरटाइम दिन', 'en': 'Overtime days'},
  'statAnnualLeave': {'tr': 'Yıllık izin', 'ur': 'سالانہ چھٹی', 'ne': 'वार्षिक बिदा', 'en': 'Annual leave'},
  'statCompOff': {'tr': 'Telafi', 'ur': 'تلافی', 'ne': 'क्षतिपूर्ति', 'en': 'Comp-off'},
  'statLate': {'tr': 'Geç kalma', 'ur': 'تاخیر', 'ne': 'ढिलाइ', 'en': 'Late'},
  'statAbsent': {'tr': 'Devamsızlık', 'ur': 'غیر حاضری', 'ne': 'अनुपस्थिति', 'en': 'Absent'},
  'groupSettings2': {'tr': 'Ayarlar', 'ur': 'ترتیبات', 'ne': 'सेटिङ', 'en': 'Settings'},
  'groupOther': {'tr': 'Diğer', 'ur': 'دیگر', 'ne': 'अन्य', 'en': 'Other'},
  'openCalendarSubtitle': {'tr': 'Takvimi aç, günü işaretle', 'ur': 'کیلنڈر کھولیں، دن نشان زد کریں', 'ne': 'क्यालेन्डर खोल्नुहोस्, दिन चिन्ह लगाउनुहोस्', 'en': 'Open the calendar, mark the day'},
  'selectMonthYear': {
    'tr': 'AY VE YIL SEC', 'ur': 'مہینہ اور سال منتخب کریں', 'ne': 'महिना र वर्ष छान्नुहोस्', 'en': 'SELECT MONTH AND YEAR',
  },
  'overtimeCalendar': {
    'tr': 'FAZLA MESAI GIRISI (TAKVIM)', 'ur': 'اضافی کام کا اندراج (کیلنڈر)', 'ne': 'ओभरटाइम प्रविष्टि (क्यालेन्डर)', 'en': 'OVERTIME ENTRY (CALENDAR)',
  },
  'salaryEmployerSettings': {
    'tr': 'MAAS VE ISVEREN AYARLARI', 'ur': 'تنخواہ اور آجر کی ترتیبات', 'ne': 'तलब र रोजगारदाता सेटिङ', 'en': 'SALARY AND EMPLOYER SETTINGS',
  },
  'startDateSettings': {
    'tr': 'ISE BASLAMA AYARLARI', 'ur': 'ملازمت شروع کرنے کی ترتیبات', 'ne': 'काम सुरु मिति सेटिङ', 'en': 'START DATE SETTINGS',
  },
  'visualSettings': {
    'tr': 'GORSEL AYARLAR', 'ur': 'بصری ترتیبات', 'ne': 'देखावट सेटिङ', 'en': 'VISUAL SETTINGS',
  },
  'taxSettings': {
    'tr': 'VERGI/ASGARI UCRET AYARLARI', 'ur': 'ٹیکس/کم از کم اجرت کی ترتیبات', 'ne': 'कर/न्यूनतम ज्याला सेटिङ', 'en': 'TAX/MINIMUM WAGE SETTINGS',
  },
  'leaveTracking': {
    'tr': 'YILLIK IZIN TAKIBI', 'ur': 'سالانہ چھٹی کا ٹریکنگ', 'ne': 'वार्षिक बिदा ट्र्याकिङ', 'en': 'ANNUAL LEAVE TRACKING',
  },
  'language': {'tr': 'DIL', 'ur': 'زبان', 'ne': 'भाषा', 'en': 'LANGUAGE'},
  'pdfExport': {
    'tr': 'PDF E AKTAR', 'ur': 'PDF میں برآمد کریں', 'ne': 'PDF मा निर्यात गर्नुहोस्', 'en': 'EXPORT TO PDF',
  },
  'encrypt': {
    'tr': 'PROGRAMI SIFRELE', 'ur': 'پروگرام کو محفوظ بنائیں', 'ne': 'प्रोग्राम लक गर्नुहोस्', 'en': 'LOCK THE APP',
  },
  'about': {'tr': 'HAKKINDA', 'ur': 'کے بارے میں', 'ne': 'बारेमा', 'en': 'ABOUT'},
  'languageScreenTitle': {
    'tr': 'Dil Ayarlari', 'ur': 'زبان کی ترتیبات', 'ne': 'भाषा सेटिङ', 'en': 'Language Settings',
  },
  'selectLanguage': {
    'tr': 'Uygulama dilini secin', 'ur': 'ایپ کی زبان منتخب کریں', 'ne': 'एपको भाषा छान्नुहोस्', 'en': 'Select app language',
  },
  'save': {'tr': 'Kaydet', 'ur': 'محفوظ کریں', 'ne': 'सुरक्षित गर्नुहोस्', 'en': 'Save'},
  'months': {
    'tr': 'Ocak,Subat,Mart,Nisan,Mayis,Haziran,Temmuz,Agustos,Eylul,Ekim,Kasim,Aralik',
    'ur': 'جنوری,فروری,مارچ,اپریل,مئی,جون,جولائی,اگست,ستمبر,اکتوبر,نومبر,دسمبر',
    'ne': 'जनवरी,फेब्रुअरी,मार्च,अप्रिल,मे,जुन,जुलाई,अगस्ट,सेप्टेम्बर,अक्टोबर,नोभेम्बर,डिसेम्बर',
    'en': 'January,February,March,April,May,June,July,August,September,October,November,December',
  },
  'calendarTitle': {'tr': 'Takvim', 'ur': 'کیلنڈر', 'ne': 'क्यालेन्डर', 'en': 'Calendar'},
  'weekdayHours': {'tr': 'Haftaici saat:', 'ur': 'ہفتے کے دن گھنٹے:', 'ne': 'हप्ताको दिन घण्टा:', 'en': 'Weekday hours:'},
  'weekdayShortHours': {'tr': 'Eksik çalışma saati:', 'ur': 'کم کام کے گھنٹے:', 'ne': 'कम काम घण्टा:', 'en': 'Short work hours:'},
  'saturdayHours': {'tr': 'Cumartesi saat:', 'ur': 'ہفتہ کے گھنٹے:', 'ne': 'शनिबार घण्टा:', 'en': 'Saturday hours:'},
  'sundayHours': {'tr': 'Pazar saat:', 'ur': 'اتوار کے گھنٹے:', 'ne': 'आइतबार घण्टा:', 'en': 'Sunday hours:'},
  'holidayHours': {'tr': 'Resmi tatil saat:', 'ur': 'سرکاری تعطیل گھنٹے:', 'ne': 'सार्वजनिक बिदा घण्टा:', 'en': 'Public holiday hours:'},
  'advanceTotal': {'tr': 'Avans toplami:', 'ur': 'کل ایڈوانس:', 'ne': 'कुल पेश्की:', 'en': 'Total advance:'},
  'tipTotal': {'tr': 'Bahsis toplami:', 'ur': 'کل انعام:', 'ne': 'कुल टिप:', 'en': 'Total tip:'},
  'normallyNetSalary': {
    'tr': '(Normalde net maas:', 'ur': '(عام طور پر خالص تنخواہ:', 'ne': '(सामान्यतया खुद तलब:', 'en': '(Normally net salary:',
  },
  'daysNetSalary': {'tr': 'gunluk net maas: +', 'ur': 'دن کی خالص تنخواہ: +', 'ne': 'दिनको खुद तलब: +', 'en': 'days net salary: +'},
  'overtimeExtra': {
    'tr': 'Fazla mesai / ekstra saat ucreti: +',
    'ur': 'اضافی وقت / اضافی گھنٹے کی اجرت: +',
    'ne': 'ओभरटाइम / अतिरिक्त घण्टा ज्याला: +',
    'en': 'Overtime / extra hour pay: +',
  },
  'finalSalary': {'tr': 'Ele gecen maas:', 'ur': 'ہاتھ میں آنے والی تنخواہ:', 'ne': 'हातमा पर्ने तलब:', 'en': 'Take-home salary:'},
  'day_officialHoliday': {
    'tr': 'Bu gun resmi tatil ve ben calistim',
    'ur': 'یہ سرکاری تعطیل ہے اور میں نے کام کیا',
    'ne': 'यो सार्वजनिक बिदा हो र मैले काम गरें',
    'en': 'This is a public holiday and I worked',
  },
  'day_overtime': {'tr': 'Fazla mesai yaptim', 'ur': 'میں نے اضافی کام کیا', 'ne': 'मैले ओभरटाइम गरें', 'en': 'I worked overtime'},
  'day_overtimeHours': {
    'tr': 'Fazla mesai saati', 'ur': 'اضافی کام کے گھنٹے', 'ne': 'ओभरटाइम घण्टा', 'en': 'Overtime hours',
  },
  'day_absent': {'tr': 'Ise gitmedim', 'ur': 'میں کام پر نہیں گیا', 'ne': 'म काममा गइनँ', 'en': "I didn't go to work"},
  'day_sick': {'tr': 'Raporluyum', 'ur': 'میں بیمار ہوں', 'ne': 'म बिरामी छु', 'en': 'I am on sick leave'},
  'day_paidLeave': {
    'tr': 'Ucretli/Yillik izindeyim', 'ur': 'میں تنخواہ دار/سالانہ چھٹی پر ہوں', 'ne': 'म तलबी/वार्षिक बिदामा छु', 'en': 'I am on paid/annual leave',
  },
  'day_unpaidLeave': {
    'tr': 'Ucretsiz izindeyim', 'ur': 'میں بلا تنخواہ چھٹی پر ہوں', 'ne': 'म बिना तलब बिदामा छु', 'en': 'I am on unpaid leave',
  },
  'day_lateMinutes': {
    'tr': 'Ise gec kaldiysaniz dakika belirtin',
    'ur': 'اگر آپ دیر سے آئے تو منٹ بتائیں',
    'ne': 'ढिलो भएमा मिनेट लेख्नुहोस्',
    'en': 'If you were late, specify the minutes',
  },
  'day_lateHours': {
    'tr': 'Kaç saat geç kaldınız / erken çıktınız?',
    'ur': 'آپ کتنے گھنٹے دیر سے آئے / جلدی گئے؟',
    'ne': 'तपाईं कति घण्टा ढिलो आउनुभयो / चाँडो जानुभयो?',
    'en': 'How many hours were you late / did you leave early?',
  },
  'day_advance': {
    'tr': 'Avans cektiyseniz belirtin', 'ur': 'اگر آپ نے ایڈوانس لیا تو بتائیں', 'ne': 'पेश्की लिनुभएको भए लेख्नुहोस्', 'en': 'If you took an advance, specify it',
  },
  'day_tip': {
    'tr': 'Bahsis/Ekstra aldiysaniz belirtin', 'ur': 'اگر آپ کو انعام/اضافی ملا تو بتائیں', 'ne': 'टिप/थप पाउनुभएको भए लेख्नुहोस्', 'en': 'If you received a tip/extra, specify it',
  },
  'day_note': {'tr': 'Notunuz', 'ur': 'آپ کا نوٹ', 'ne': 'तपाईंको नोट', 'en': 'Your note'},
  'delete': {'tr': 'Sil', 'ur': 'حذف کریں', 'ne': 'मेटाउनुहोस्', 'en': 'Delete'},
  'cancel': {'tr': 'VAZGEC', 'ur': 'منسوخ کریں', 'ne': 'रद्द गर्नुहोस्', 'en': 'CANCEL'},
  'ok': {'tr': 'TAMAM', 'ur': 'ٹھیک ہے', 'ne': 'ठीक छ', 'en': 'OK'},
  'salaryEmployerSettingsTitle': {
    'tr': 'Maas ve Isveren Ayarlari', 'ur': 'تنخواہ اور آجر ترتیبات', 'ne': 'तलब र रोजगारदाता सेटिङ', 'en': 'Salary and Employer Settings',
  },
  'salaryTab': {'tr': 'MAAS AYARLARI', 'ur': 'تنخواہ ترتیبات', 'ne': 'तलब सेटिङ', 'en': 'SALARY SETTINGS'},
  'employerTab': {'tr': 'ISVEREN AYARLARI', 'ur': 'آجر ترتیبات', 'ne': 'रोजगारदाता सेटिङ', 'en': 'EMPLOYER SETTINGS'},
  'iptalBtn': {'tr': 'Iptal', 'ur': 'منسوخ کریں', 'ne': 'रद्द गर्नुहोस्', 'en': 'Cancel'},
  'workType': {'tr': 'Calisma tipi', 'ur': 'کام کی قسم', 'ne': 'काम को प्रकार', 'en': 'Work type'},
  'hourlyPaid': {'tr': 'Saatlik ucretli', 'ur': 'فی گھنٹہ اجرت', 'ne': 'प्रति घण्टा ज्याला', 'en': 'Hourly paid'},
  'monthlyPaid': {'tr': 'Aylik maasli', 'ur': 'ماہانہ تنخواہ', 'ne': 'मासिक तलब', 'en': 'Monthly salaried'},
  'hourlyInfoText': {
    'tr': 'Saatlik ucretiniz ve standart aylik saatinizden bir net maas hesaplanir, bu maas ayin gun sayisina gore olceklenir. Takvime girdiginiz ekstra saatler ayrica eklenir.',
    'ur': 'آپ کی فی گھنٹہ اجرت اور معیاری ماہانہ گھنٹوں سے ایک خالص تنخواہ کا حساب لگایا جاتا ہے، یہ تنخواہ مہینے کے دنوں کی تعداد کے مطابق ایڈجسٹ ہوتی ہے۔ کیلنڈر میں درج اضافی گھنٹے الگ سے شامل کیے جاتے ہیں۔',
    'ne': 'तपाईंको प्रति घण्टा ज्याला र मानक मासिक घण्टाबाट खुद तलब गणना गरिन्छ, यो तलब महिनाको दिन संख्या अनुसार समायोजन गरिन्छ। क्यालेन्डरमा प्रविष्ट गरिएका थप घण्टाहरू छुट्टै थपिन्छ।',
    'en': 'A net salary is calculated from your hourly rate and standard monthly hours, and it is scaled according to the number of days in the month. Extra hours you enter in the calendar are added separately.',
  },
  'hourlyRateLabel': {'tr': 'Saatlik ucretiniz (TL)', 'ur': 'آپ کی فی گھنٹہ اجرت (TL)', 'ne': 'तपाईंको प्रति घण्टा ज्याला (TL)', 'en': 'Your hourly rate (TL)'},
  'standardHoursLabel': {
    'tr': 'Standart aylik saat (orn. 225, 30 gun icin)',
    'ur': 'معیاری ماہانہ گھنٹے (مثلاً 225، 30 دن کے لیے)',
    'ne': 'मानक मासिक घण्टा (जस्तै 225, 30 दिनको लागि)',
    'en': 'Standard monthly hours (e.g. 225, for 30 days)',
  },
  'salaryCalcMethod': {'tr': 'Maas nasil hesaplansin', 'ur': 'تنخواہ کیسے شمار کی جائے', 'ne': 'तलब कसरी गणना गर्ने', 'en': 'How should salary be calculated'},
  'calcFromGross': {
    'tr': 'Brut maas uzerinden otomatik hesapla', 'ur': 'مجموعی تنخواہ سے خودکار حساب لگائیں', 'ne': 'कुल तलबबाट स्वचालित गणना गर्नुहोस्', 'en': 'Calculate automatically from gross salary',
  },
  'calcFromNet': {
    'tr': 'Net maas uzerinden otomatik hesapla', 'ur': 'خالص تنخواہ سے خودکار حساب لگائیں', 'ne': 'खुद तलबबाट स्वचालित गणना गर्नुहोस्', 'en': 'Calculate automatically from net salary',
  },
  'calcManual': {
    'tr': 'Manuel: net maasi ben gireceğim', 'ur': 'دستی: میں خالص تنخواہ خود درج کروں گا', 'ne': 'म्यानुअल: म खुद तलब आफैं प्रविष्ट गर्नेछु', 'en': 'Manual: I will enter the net salary myself',
  },
  'grossSalaryLabel': {'tr': 'Brut maasiniz (30 gun icin)', 'ur': 'آپ کی مجموعی تنخواہ (30 دن کے لیے)', 'ne': 'तपाईंको कुल तलब (30 दिनको लागि)', 'en': 'Your gross salary (for 30 days)'},
  'sgkShare': {'tr': 'SGK Isci Payi', 'ur': 'SGK ملازم حصہ', 'ne': 'SGK कर्मचारी हिस्सा', 'en': 'SGK Employee Share'},
  'unemploymentShare': {'tr': 'Issiz. Sigortasi Payi', 'ur': 'بے روزگاری انشورنس حصہ', 'ne': 'बेरोजगारी बीमा हिस्सा', 'en': 'Unemployment Insurance Share'},
  'incomeTaxBase': {'tr': 'Bu Ayki Gelir Vergisi Matrahi', 'ur': 'اس ماہ کی انکم ٹیکس بنیاد', 'ne': 'यस महिनाको आयकर आधार', 'en': "This Month's Income Tax Base"},
  'incomeTax': {'tr': 'Gelir Vergisi', 'ur': 'انکم ٹیکس', 'ne': 'आयकर', 'en': 'Income Tax'},
  'stampTax': {'tr': 'Damga Vergisi', 'ur': 'اسٹامپ ڈیوٹی', 'ne': 'स्ट्याम्प कर', 'en': 'Stamp Tax'},
  'totalDeductions': {'tr': 'Kesintiler Toplami', 'ur': 'کل کٹوتیاں', 'ne': 'कुल कटौती', 'en': 'Total Deductions'},
  'netSalaryLabel30': {'tr': 'Net maasiniz (30 gun icin)', 'ur': 'آپ کی خالص تنخواہ (30 دن کے لیے)', 'ne': 'तपाईंको खुद तलब (30 दिनको लागि)', 'en': 'Your net salary (for 30 days)'},
  'netSalaryManualLabel': {
    'tr': 'Net maasiniz (30 gun icin, elle girin)', 'ur': 'آپ کی خالص تنخواہ (30 دن، دستی طور پر درج کریں)', 'ne': 'तपाईंको खुद तलब (30 दिन, आफैं प्रविष्ट गर्नुहोस्)', 'en': 'Your net salary (for 30 days, enter manually)',
  },
  'weekendDeductions': {'tr': 'Hafta tatili kesintileri', 'ur': 'ہفتہ وار چھٹی کٹوتیاں', 'ne': 'साप्ताहिक बिदा कटौती', 'en': 'Weekend deductions'},
  'overtimeMultipliersTitle': {'tr': 'Fazla mesai carpanlari', 'ur': 'اضافی وقت کے ضرب', 'ne': 'ओभरटाइम गुणक', 'en': 'Overtime multipliers'},
  'weekdayMultiplierLabel': {'tr': 'Haftaici carpani (orn. 1.5)', 'ur': 'ہفتہ کے دن کا ضرب (مثلاً 1.5)', 'ne': 'हप्ताको दिन गुणक (जस्तै 1.5)', 'en': 'Weekday multiplier (e.g. 1.5)'},
  'saturdayMultiplierLabel': {'tr': 'Cumartesi carpani (orn. 1.5)', 'ur': 'ہفتے کا ضرب (مثلاً 1.5)', 'ne': 'शनिबार गुणक (जस्तै 1.5)', 'en': 'Saturday multiplier (e.g. 1.5)'},
  'sundayMultiplierLabel': {'tr': 'Pazar carpani (orn. 2.0)', 'ur': 'اتوار کا ضرب (مثلاً 2.0)', 'ne': 'आइतबार गुणक (जस्तै 2.0)', 'en': 'Sunday multiplier (e.g. 2.0)'},
  'holidayMultiplierLabel': {'tr': 'Resmi tatil carpani (orn. 2.0)', 'ur': 'سرکاری تعطیل کا ضرب (مثلاً 2.0)', 'ne': 'सार्वजनिक बिदा गुणक (जस्तै 2.0)', 'en': 'Public holiday multiplier (e.g. 2.0)'},
  'hourlyRateResult': {'tr': '1 saatlik ucretiniz', 'ur': 'آپ کی 1 گھنٹے کی اجرت', 'ne': 'तपाईंको १ घण्टा ज्याला', 'en': 'Your hourly rate'},
  'weekdayHourlyRate': {'tr': 'Haftaici 1 saat ucret', 'ur': 'ہفتہ کے دن 1 گھنٹے کی اجرت', 'ne': 'हप्ताको दिन १ घण्टा ज्याला', 'en': 'Weekday hourly rate'},
  'saturdayHourlyRate': {'tr': 'Cumartesi 1 saat ucret', 'ur': 'ہفتے 1 گھنٹے کی اجرت', 'ne': 'शनिबार १ घण्टा ज्याला', 'en': 'Saturday hourly rate'},
  'sundayHourlyRate': {'tr': 'Pazar 1 saat ucret', 'ur': 'اتوار 1 گھنٹے کی اجرت', 'ne': 'आइतबार १ घण्टा ज्याला', 'en': 'Sunday hourly rate'},
  'holidayHourlyRate': {'tr': 'Resmi tatil 1 saat ucret', 'ur': 'سرکاری تعطیل 1 گھنٹے کی اجرت', 'ne': 'सार्वजनिक बिदा १ घण्टा ज्याला', 'en': 'Public holiday hourly rate'},
  'monthlyNetSalaryText': {
    'tr': 'Bu ay (%d gun) icin net maas: ', 'ur': 'اس مہینے (%d دن) کی خالص تنخواہ: ', 'ne': 'यस महिना (%d दिन) को खुद तलब: ', 'en': 'Net salary for this month (%d days): ',
  },
  'employerHolidayQuestion': {
    'tr': 'ISVERENINIZ RESMI TATIL CALISMALARININ UCRETLERINI NASIL HESAPLAR?',
    'ur': 'آپ کا آجر سرکاری تعطیل کے کام کی اجرت کیسے شمار کرتا ہے؟',
    'ne': 'तपाईंको रोजगारदाताले सार्वजनिक बिदाको काम कसरी गणना गर्छ?',
    'en': 'HOW DOES YOUR EMPLOYER CALCULATE PUBLIC HOLIDAY WORK PAY?',
  },
  'holidayOptionExtraDay': {
    'tr': 'Resmi tatilde calistiginizda fazladan bir gunluk ucret veriyorsa bu secenegi isaretleyin.',
    'ur': 'اگر سرکاری تعطیل پر کام کرنے پر ایک اضافی دن کی اجرت ملتی ہے تو یہ آپشن منتخب کریں۔',
    'ne': 'सार्वजनिक बिदामा काम गर्दा थप एक दिनको ज्याला दिने भए यो विकल्प छान्नुहोस्।',
    'en': 'Select this option if you receive an extra day of pay for working on a public holiday.',
  },
  'holidayOptionOvertime': {
    'tr': 'Isvereniniz resmi tatildeki tum calismanizi fazla mesai olarak oduyorsa bu secenegi isaretleyin.',
    'ur': 'اگر آجر سرکاری تعطیل کے تمام کام کو اضافی وقت کے طور پر ادا کرتا ہے تو یہ آپشن منتخب کریں۔',
    'ne': 'रोजगारदाताले सार्वजनिक बिदाको सबै काम ओभरटाइमको रूपमा तिर्ने भए यो विकल्प छान्नुहोस्।',
    'en': 'Select this option if your employer pays all your public holiday work as overtime.',
  },
  'employerNetSalaryQuestion': {
    'tr': 'ISVERENINIZ NET MAASI NASIL HESAPLAR?', 'ur': 'آپ کا آجر خالص تنخواہ کیسے شمار کرتا ہے؟', 'ne': 'तपाईंको रोजगारदाताले खुद तलब कसरी गणना गर्छ?', 'en': 'HOW DOES YOUR EMPLOYER CALCULATE NET SALARY?',
  },
  'fixedSalaryOption': {
    'tr': 'Isvereniniz sabit net maas oduyorsa bu secenegi isaretleyin (ay 28-29-31 gun de olsa maas ayni).',
    'ur': 'اگر آجر مقررہ خالص تنخواہ دیتا ہے تو یہ آپشن منتخب کریں (مہینہ 28-29-31 دن کا ہو تب بھی تنخواہ ایک جیسی)۔',
    'ne': 'रोजगारदाताले स्थिर खुद तलब तिर्ने भए यो विकल्प छान्नुहोस् (महिना २८-२९-३१ दिनको भए पनि तलब उही)।',
    'en': 'Select this option if your employer pays a fixed net salary (same salary whether the month has 28, 29 or 31 days).',
  },
  'dayBasedSalaryOption': {
    'tr': 'Isvereniniz net maasi aydaki gun sayisina gore hesapliyorsa bu secenegi isaretleyin.',
    'ur': 'اگر آجر خالص تنخواہ مہینے کے دنوں کی تعداد کے مطابق شمار کرتا ہے تو یہ آپشن منتخب کریں۔',
    'ne': 'रोजगारदाताले खुद तलब महिनाको दिन संख्या अनुसार गणना गर्ने भए यो विकल्प छान्नुहोस्।',
    'en': "Select this option if your employer calculates net salary based on the number of days in the month.",
  },
  'employerSickPayQuestion': {
    'tr': 'ISVERENINIZ RAPORLU GUN UCRETLERINI NASIL HESAPLAR?', 'ur': 'آپ کا آجر بیماری کی چھٹی کی اجرت کیسے شمار کرتا ہے؟', 'ne': 'तपाईंको रोजगारदाताले बिरामी बिदाको ज्याला कसरी गणना गर्छ?', 'en': 'HOW DOES YOUR EMPLOYER CALCULATE SICK LEAVE PAY?',
  },
  'sickPayNone': {
    'tr': 'Isvereniniz raporlu oldugunuz gunler icin odeme yapmiyorsa bu secenegi isaretleyin.',
    'ur': 'اگر آجر بیماری کی چھٹی کے دنوں کی ادائیگی نہیں کرتا تو یہ آپشن منتخب کریں۔',
    'ne': 'रोजगारदाताले बिरामी बिदाको दिनको भुक्तानी नगर्ने भए यो विकल्प छान्नुहोस्।',
    'en': 'Select this option if your employer does not pay for the days you are on sick leave.',
  },
  'sickPayFirst2Days': {
    'tr': 'Isvereniniz raporlu oldugunuz ilk 2 gune odeme yapmiyor, diger gunlere odeme yapiyorsa bu secenegi isaretleyin.',
    'ur': 'اگر آجر پہلے 2 دنوں کی ادائیگی نہیں کرتا مگر باقی دنوں کی کرتا ہے تو یہ آپشن منتخب کریں۔',
    'ne': 'रोजगारदाताले पहिलो २ दिनको भुक्तानी नगरी बाँकी दिनको गर्ने भए यो विकल्प छान्नुहोस्।',
    'en': 'Select this option if your employer does not pay for the first 2 sick days but pays for the rest.',
  },
  'sickPayAllDays': {
    'tr': 'Isvereniniz raporlu oldugunuz butun gunler icin odeme yapiyorsa bu secenegi isaretleyin.',
    'ur': 'اگر آجر بیماری کی چھٹی کے تمام دنوں کی ادائیگی کرتا ہے تو یہ آپشن منتخب کریں۔',
    'ne': 'रोजगारदाताले बिरामी बिदाको सबै दिनको भुक्तानी गर्ने भए यो विकल्प छान्नुहोस्।',
    'en': 'Select this option if your employer pays for all your sick leave days.',
  },
  'mon': {'tr': 'Pzt', 'ur': 'پیر', 'ne': 'सोम', 'en': 'Mon'},
  'tue': {'tr': 'Sal', 'ur': 'منگل', 'ne': 'मंगल', 'en': 'Tue'},
  'wed': {'tr': 'Çar', 'ur': 'بدھ', 'ne': 'बुध', 'en': 'Wed'},
  'thu': {'tr': 'Per', 'ur': 'جمعرات', 'ne': 'बिहि', 'en': 'Thu'},
  'fri': {'tr': 'Cum', 'ur': 'جمعہ', 'ne': 'शुक्र', 'en': 'Fri'},
  'sat': {'tr': 'Cmt', 'ur': 'ہفتہ', 'ne': 'शनि', 'en': 'Sat'},
  'sun': {'tr': 'Paz', 'ur': 'اتوار', 'ne': 'आइत', 'en': 'Sun'},
  'startDateTitle': {'tr': 'Ise Baslama Ayarlari', 'ur': 'ملازمت شروع کرنے کی ترتیبات', 'ne': 'काम सुरु मिति सेटिङ', 'en': 'Start Date Settings'},
  'startDateLabel': {'tr': 'Ise baslama tarihiniz', 'ur': 'آپ کی ملازمت شروع ہونے کی تاریخ', 'ne': 'तपाईंको काम सुरु मिति', 'en': 'Your start date'},
  'pickDate': {'tr': 'Tarih secin', 'ur': 'تاریخ منتخب کریں', 'ne': 'मिति छान्नुहोस्', 'en': 'Select date'},
  'annualLeaveLabel': {'tr': 'Yillik izin hakkiniz (gun)', 'ur': 'آپ کی سالانہ چھٹی کا حق (دن)', 'ne': 'तपाईंको वार्षिक बिदा अधिकार (दिन)', 'en': 'Your annual leave entitlement (days)'},
  'exampleFourteen': {'tr': 'Orn. 14', 'ur': 'مثلاً 14', 'ne': 'जस्तै 14', 'en': 'E.g. 14'},
  'visualSettingsTitle': {'tr': 'Gorsel Ayarlar', 'ur': 'بصری ترتیبات', 'ne': 'देखावट सेटिङ', 'en': 'Visual Settings'},
  'themeSelection': {'tr': 'Tema secimi', 'ur': 'تھیم کا انتخاب', 'ne': 'थिम छनोट', 'en': 'Theme selection'},
  'themeSystem': {'tr': 'Telefon ayarina gore (otomatik)', 'ur': 'فون کی ترتیبات کے مطابق (خودکار)', 'ne': 'फोन सेटिङ अनुसार (स्वचालित)', 'en': 'Follow phone setting (automatic)'},
  'themeLight': {'tr': 'Acik tema', 'ur': 'روشن تھیم', 'ne': 'उज्यालो थिम', 'en': 'Light theme'},
  'themeDark': {'tr': 'Koyu tema', 'ur': 'گہرا تھیم', 'ne': 'गाढा थिम', 'en': 'Dark theme'},
  'taxScreenTitle': {'tr': 'Vergi ve Asgari Ucret Ayarlari', 'ur': 'ٹیکس اور کم از کم اجرت کی ترتیبات', 'ne': 'कर र न्यूनतम ज्याला सेटिङ', 'en': 'Tax and Minimum Wage Settings'},
  'selectYear': {'tr': 'Yil secin', 'ur': 'سال منتخب کریں', 'ne': 'वर्ष छान्नुहोस्', 'en': 'Select year'},
  'noOwnDataWarning': {
    'tr': 'Bu yil icin henuz ayri deger girilmedi. Onceki yildan tasinan degerler gosteriliyor. Yeni oranlar aciklaninca guncelleyip kaydedin.',
    'ur': 'اس سال کے لیے ابھی تک الگ ویلیو درج نہیں کی گئی۔ پچھلے سال کی ویلیوز دکھائی جا رہی ہیں۔ نئی شرحیں اعلان ہونے پر اپ ڈیٹ کر کے محفوظ کریں۔',
    'ne': 'यस वर्षको लागि अझै छुट्टै मान प्रविष्ट गरिएको छैन। अघिल्लो वर्षका मानहरू देखाइँदैछ। नयाँ दरहरू घोषणा भएपछि अद्यावधिक गरी सुरक्षित गर्नुहोस्।',
    'en': 'No separate value has been entered for this year yet. Values carried over from the previous year are shown. Update and save once new rates are announced.',
  },
  'deductionRatesTitle': {'tr': 'Kesinti oranlari (%)', 'ur': 'کٹوتی کی شرحیں (%)', 'ne': 'कटौती दरहरू (%)', 'en': 'Deduction rates (%)'},
  'sgkShareLabel': {'tr': 'SGK Isci Payi (%)', 'ur': 'SGK ملازم حصہ (%)', 'ne': 'SGK कर्मचारी हिस्सा (%)', 'en': 'SGK Employee Share (%)'},
  'unemploymentShareLabel': {'tr': 'Issizlik Sigortasi Payi (%)', 'ur': 'بے روزگاری انشورنس حصہ (%)', 'ne': 'बेरोजगारी बीमा हिस्सा (%)', 'en': 'Unemployment Insurance Share (%)'},
  'incomeTaxLabel': {'tr': 'Gelir Vergisi (%)', 'ur': 'انکم ٹیکس (%)', 'ne': 'आयकर (%)', 'en': 'Income Tax (%)'},
  'stampTaxLabel': {'tr': 'Damga Vergisi (%)', 'ur': 'اسٹامپ ڈیوٹی (%)', 'ne': 'स्ट्याम्प कर (%)', 'en': 'Stamp Tax (%)'},
  'minWageTitle': {'tr': 'Asgari ucret', 'ur': 'کم از کم اجرت', 'ne': 'न्यूनतम ज्याला', 'en': 'Minimum wage'},
  'minWageGrossLabel': {'tr': 'Asgari ucret brut (TL)', 'ur': 'کم از کم اجرت مجموعی (TL)', 'ne': 'न्यूनतम ज्याला कुल (TL)', 'en': 'Minimum wage gross (TL)'},
  'minWageNetLabel': {'tr': 'Asgari ucret net (TL)', 'ur': 'کم از کم اجرت خالص (TL)', 'ne': 'न्यूनतम ज्याला खुद (TL)', 'en': 'Minimum wage net (TL)'},
  'saveForYear': {'tr': 'yili icin kaydet', 'ur': 'سال کے لیے محفوظ کریں', 'ne': 'वर्षको लागि सुरक्षित गर्नुहोस्', 'en': 'save for year'},
  'taxSavedSnackbar': {'tr': 'yili vergi ayarlari kaydedildi', 'ur': 'سال کی ٹیکس ترتیبات محفوظ ہو گئیں', 'ne': 'वर्षको कर सेटिङ सुरक्षित भयो', 'en': 'tax settings for year saved'},
  'taxYearNote': {
    'tr': 'Not: Her yil icin degerler ayri saklanir. Yeni yil oranlari resmi olarak aciklandiginda bu ekrandan o yili secip degerleri guncelleyin. Guncellenmeyen yillar bir onceki yilin oranlarini kullanmaya devam eder.',
    'ur': 'نوٹ: ہر سال کی ویلیوز الگ محفوظ کی جاتی ہیں۔ نئے سال کی شرحیں سرکاری طور پر اعلان ہونے پر اس اسکرین سے وہ سال منتخب کر کے ویلیوز اپ ڈیٹ کریں۔ اپ ڈیٹ نہ ہونے والے سال پچھلے سال کی شرحیں استعمال کرتے رہیں گے۔',
    'ne': 'नोट: प्रत्येक वर्षको मान छुट्टै सुरक्षित गरिन्छ। नयाँ वर्षका दरहरू आधिकारिक रूपमा घोषणा भएपछि यस स्क्रिनबाट त्यो वर्ष छानी मानहरू अद्यावधिक गर्नुहोस्। अद्यावधिक नगरिएका वर्षहरूले अघिल्लो वर्षका दरहरू प्रयोग गर्न जारी राख्नेछन्।',
    'en': "Note: Values are stored separately for each year. When new yearly rates are officially announced, select that year on this screen and update the values. Years that are not updated will continue to use the previous year's rates.",
  },
  'leaveScreenTitle': {'tr': 'Yillik Izin Takibi', 'ur': 'سالانہ چھٹی کا ٹریکنگ', 'ne': 'वार्षिक बिदा ट्र्याकिङ', 'en': 'Annual Leave Tracking'},
  'serviceDuration': {'tr': 'Hizmet suresi:', 'ur': 'ملازمت کی مدت:', 'ne': 'सेवा अवधि:', 'en': 'Length of service:'},
  'yearsSuffix': {'tr': 'yil', 'ur': 'سال', 'ne': 'वर्ष', 'en': 'years'},
  'monthsSuffix': {'tr': 'ay', 'ur': 'مہینے', 'ne': 'महिना', 'en': 'months'},
  'annualLeaveRight': {'tr': 'Yillik izin hakki:', 'ur': 'سالانہ چھٹی کا حق:', 'ne': 'वार्षिक बिदा अधिकार:', 'en': 'Annual leave entitlement:'},
  'usedDays': {'tr': 'Kullanilan:', 'ur': 'استعمال شدہ:', 'ne': 'प्रयोग गरिएको:', 'en': 'Used:'},
  'remainingDays': {'tr': 'Kalan:', 'ur': 'باقی:', 'ne': 'बाँकी:', 'en': 'Remaining:'},
  'daySuffix': {'tr': 'gun', 'ur': 'دن', 'ne': 'दिन', 'en': 'days'},
  'usedLeaveDaysTitle': {'tr': 'Kullanilan izin gunleri', 'ur': 'استعمال شدہ چھٹی کے دن', 'ne': 'प्रयोग गरिएका बिदा दिनहरू', 'en': 'Used leave days'},
  'noLeaveUsedThisYear': {'tr': 'Bu yil izin kullanilmadi', 'ur': 'اس سال چھٹی استعمال نہیں کی گئی', 'ne': 'यस वर्ष बिदा प्रयोग गरिएन', 'en': 'No leave used this year'},
  'pdfExportTitle': {'tr': 'PDF e Aktar', 'ur': 'PDF میں برآمد کریں', 'ne': 'PDF मा निर्यात गर्नुहोस्', 'en': 'Export to PDF'},
  'typeOvertime': {'tr': 'Fazla Mesai', 'ur': 'اضافی کام', 'ne': 'ओभरटाइम', 'en': 'Overtime'},
  'typeAbsent': {'tr': 'Ise Gitmedim', 'ur': 'کام پر نہیں گیا', 'ne': 'काममा गइनँ', 'en': 'Absent'},
  'typeSick': {'tr': 'Raporlu', 'ur': 'بیماری کی چھٹی', 'ne': 'बिरामी बिदा', 'en': 'Sick leave'},
  'typePaidLeave': {'tr': 'Ucretli Izin', 'ur': 'تنخواہ دار چھٹی', 'ne': 'तलबी बिदा', 'en': 'Paid leave'},
  'typeUnpaidLeave': {'tr': 'Ucretsiz Izin', 'ur': 'بلا تنخواہ چھٹی', 'ne': 'बिना तलब बिदा', 'en': 'Unpaid leave'},
  'noRecordText': {'tr': 'Kayit yok', 'ur': 'کوئی ریکارڈ نہیں', 'ne': 'रेकर्ड छैन', 'en': 'No record'},
  'pdfReportTitle': {'tr': 'Mesaimatik - Aylik Rapor', 'ur': 'Mesaimatik - ماہانہ رپورٹ', 'ne': 'Mesaimatik - मासिक रिपोर्ट', 'en': 'Mesaimatik - Monthly Report'},
  'pdfHeaderDate': {'tr': 'Tarih', 'ur': 'تاریخ', 'ne': 'मिति', 'en': 'Date'},
  'pdfHeaderStatus': {'tr': 'Durum', 'ur': 'حالت', 'ne': 'स्थिति', 'en': 'Status'},
  'pdfHeaderHours': {'tr': 'Saat', 'ur': 'گھنٹے', 'ne': 'घण्टा', 'en': 'Hours'},
  'pdfHeaderAdvance': {'tr': 'Avans', 'ur': 'ایڈوانس', 'ne': 'पेश्की', 'en': 'Advance'},
  'pdfHeaderTip': {'tr': 'Bahsis', 'ur': 'انعام', 'ne': 'टिप', 'en': 'Tip'},
  'pdfHeaderNote': {'tr': 'Not', 'ur': 'نوٹ', 'ne': 'नोट', 'en': 'Note'},
  'pdfSummaryTitle': {'tr': 'Ozet', 'ur': 'خلاصہ', 'ne': 'सारांश', 'en': 'Summary'},
  'pdfWeekdayOvertime': {'tr': 'Haftaici fazla mesai:', 'ur': 'ہفتہ کے دن اضافی کام:', 'ne': 'हप्ताको दिन ओभरटाइम:', 'en': 'Weekday overtime:'},
  'pdfSaturdayOvertime': {'tr': 'Cumartesi fazla mesai:', 'ur': 'ہفتے کا اضافی کام:', 'ne': 'शनिबार ओभरटाइम:', 'en': 'Saturday overtime:'},
  'pdfSundayOvertime': {'tr': 'Pazar fazla mesai:', 'ur': 'اتوار کا اضافی کام:', 'ne': 'आइतबार ओभरटाइम:', 'en': 'Sunday overtime:'},
  'pdfHolidayOvertime': {'tr': 'Resmi tatil fazla mesai:', 'ur': 'سرکاری تعطیل اضافی کام:', 'ne': 'सार्वजनिक बिदा ओभरटाइम:', 'en': 'Public holiday overtime:'},
  'hoursSuffix': {'tr': 'saat', 'ur': 'گھنٹے', 'ne': 'घण्टा', 'en': 'hours'},
  'pdfAdvanceTotal': {'tr': 'Avans toplami:', 'ur': 'کل ایڈوانس:', 'ne': 'कुल पेश्की:', 'en': 'Total advance:'},
  'pdfTipTotal': {'tr': 'Bahsis toplami:', 'ur': 'کل انعام:', 'ne': 'कुल टिप:', 'en': 'Total tip:'},
  'pdfNormalEarning': {'tr': 'Normal kazanc:', 'ur': 'عام آمدنی:', 'ne': 'सामान्य आम्दानी:', 'en': 'Normal earning:'},
  'pdfOvertimePay': {'tr': 'Fazla mesai ucreti:', 'ur': 'اضافی کام کی اجرت:', 'ne': 'ओभरटाइम ज्याला:', 'en': 'Overtime pay:'},
  'pdfFinalSalary': {'tr': 'Ele gecen maas:', 'ur': 'ہاتھ میں آنے والی تنخواہ:', 'ne': 'हातमा पर्ने तलब:', 'en': 'Take-home salary:'},
  'pdfCreatedSnackbar': {'tr': 'PDF olusturuldu', 'ur': 'PDF بن گئی', 'ne': 'PDF बनाइयो', 'en': 'PDF created'},
  'whichMonthQuestion': {'tr': 'Hangi ayin raporunu olusturmak istiyorsunuz?', 'ur': 'آپ کس مہینے کی رپورٹ بنانا چاہتے ہیں؟', 'ne': 'तपाईं कुन महिनाको रिपोर्ट बनाउन चाहनुहुन्छ?', 'en': "Which month's report would you like to create?"},
  'generatingText': {'tr': 'Olusturuluyor...', 'ur': 'بنایا جا رہا ہے...', 'ne': 'बनाइँदैछ...', 'en': 'Generating...'},
  'generatePdfButton': {'tr': 'PDF Olustur ve Paylas', 'ur': 'PDF بنائیں اور شیئر کریں', 'ne': 'PDF बनाउनुहोस् र साझा गर्नुहोस्', 'en': 'Create and Share PDF'},
  'shareInfoText': {'tr': 'PDF olusturulduktan sonra telefonunuzun paylasim menusu acilacak.', 'ur': 'PDF بننے کے بعد آپ کے فون کا شیئر مینو کھلے گا۔', 'ne': 'PDF बनेपछि तपाईंको फोनको सेयर मेनु खुल्नेछ।', 'en': "After the PDF is created, your phone's share menu will open."},
  'encryptScreenTitle': {'tr': 'Programi Sifrele', 'ur': 'پروگرام کو محفوظ بنائیں', 'ne': 'प्रोग्राम लक गर्नुहोस्', 'en': 'Lock the App'},
  'pinMinLengthError': {'tr': 'PIN en az 4 haneli olmali', 'ur': 'PIN کم از کم 4 ہندسوں کا ہونا چاہیے', 'ne': 'PIN कम्तिमा ४ अंकको हुनुपर्छ', 'en': 'PIN must be at least 4 digits'},
  'pinMismatchError': {'tr': 'PIN ler eslesmiyor', 'ur': 'PIN میل نہیں کھاتے', 'ne': 'PIN मिलेन', 'en': 'PINs do not match'},
  'pinSavedMessage': {'tr': 'PIN kaydedildi. Uygulama bir sonraki acilista PIN isteyecek.', 'ur': 'PIN محفوظ ہو گیا۔ اگلی بار ایپ کھلنے پر PIN مانگا جائے گا۔', 'ne': 'PIN सुरक्षित भयो। अर्को पटक एप खोल्दा PIN सोधिनेछ।', 'en': 'PIN saved. The app will ask for the PIN next time it opens.'},
  'wrongCurrentPinError': {'tr': 'Mevcut PIN yanlis', 'ur': 'موجودہ PIN غلط ہے', 'ne': 'हालको PIN गलत छ', 'en': 'Current PIN is incorrect'},
  'pinRemovedMessage': {'tr': 'PIN kaldirildi.', 'ur': 'PIN ہٹا دیا گیا۔', 'ne': 'PIN हटाइयो।', 'en': 'PIN removed.'},
  'pinActiveMessage': {'tr': 'Uygulama su an PIN ile korunuyor.', 'ur': 'ایپ فی الحال PIN سے محفوظ ہے۔', 'ne': 'एप हाल PIN द्वारा सुरक्षित छ।', 'en': 'The app is currently protected with a PIN.'},
  'enterCurrentPinToRemove': {'tr': 'PIN i kaldirmak icin mevcut PIN i girin:', 'ur': 'PIN ہٹانے کے لیے موجودہ PIN درج کریں:', 'ne': 'PIN हटाउन हालको PIN प्रविष्ट गर्नुहोस्:', 'en': 'Enter your current PIN to remove it:'},
  'currentPinLabel': {'tr': 'Mevcut PIN', 'ur': 'موجودہ PIN', 'ne': 'हालको PIN', 'en': 'Current PIN'},
  'removePinButton': {'tr': 'PIN i Kaldir', 'ur': 'PIN ہٹائیں', 'ne': 'PIN हटाउनुहोस्', 'en': 'Remove PIN'},
  'pinNotActiveMessage': {'tr': 'Uygulama su an PIN ile korunmuyor.', 'ur': 'ایپ فی الحال PIN سے محفوظ نہیں ہے۔', 'ne': 'एप हाल PIN द्वारा सुरक्षित छैन।', 'en': 'The app is not currently protected with a PIN.'},
  'changePinTitle': {'tr': 'PIN i degistir:', 'ur': 'PIN تبدیل کریں:', 'ne': 'PIN परिवर्तन गर्नुहोस्:', 'en': 'Change PIN:'},
  'newPinTitle': {'tr': 'Yeni bir PIN belirleyin (4 haneli):', 'ur': 'ایک نیا PIN مقرر کریں (4 ہندسوں کا):', 'ne': 'नयाँ PIN सेट गर्नुहोस् (४ अंकको):', 'en': 'Set a new PIN (4 digits):'},
  'newPinLabel': {'tr': 'Yeni PIN', 'ur': 'نیا PIN', 'ne': 'नयाँ PIN', 'en': 'New PIN'},
  'confirmPinLabel': {'tr': 'Yeni PIN (tekrar)', 'ur': 'نیا PIN (دوبارہ)', 'ne': 'नयाँ PIN (फेरि)', 'en': 'New PIN (repeat)'},
  'updatePinButton': {'tr': 'PIN i Guncelle', 'ur': 'PIN اپ ڈیٹ کریں', 'ne': 'PIN अद्यावधिक गर्नुहोस्', 'en': 'Update PIN'},
  'setPinButton': {'tr': 'PIN Belirle', 'ur': 'PIN مقرر کریں', 'ne': 'PIN सेट गर्नुहोस्', 'en': 'Set PIN'},
  'aboutTitle': {'tr': 'Hakkinda', 'ur': 'کے بارے میں', 'ne': 'बारेमा', 'en': 'About'},
  'versionLabel': {'tr': 'Surum: 1.0.0', 'ur': 'ورژن: 1.0.0', 'ne': 'संस्करण: 1.0.0', 'en': 'Version: 1.0.0'},
  'aboutDescription': {
    'tr': 'Bu uygulama, calisanlarin fazla mesai saatlerini takip etmesi ve maas hesaplamalarini yapabilmesi icin gelistirilmistir.',
    'ur': 'یہ ایپ ملازمین کو اضافی کام کے اوقات ٹریک کرنے اور تنخواہ کا حساب لگانے کے لیے بنائی گئی ہے۔',
    'ne': 'यो एप कर्मचारीहरूले ओभरटाइम घण्टा ट्र्याक गर्न र तलब गणना गर्न सक्ने बनाइएको हो।',
    'en': 'This app was developed to help employees track their overtime hours and calculate their salary.',
  },
  'featuresTitle': {'tr': 'Ozellikler:', 'ur': 'خصوصیات:', 'ne': 'सुविधाहरू:', 'en': 'Features:'},
  'feature1': {'tr': '- Gunluk fazla mesai takibi', 'ur': '- روزانہ اضافی کام کا ٹریکنگ', 'ne': '- दैनिक ओभरटाइम ट्र्याकिङ', 'en': '- Daily overtime tracking'},
  'feature2': {'tr': '- Haftaici / Cumartesi / Pazar / Resmi tatil ayrimi', 'ur': '- ہفتہ کے دن / ہفتہ / اتوار / سرکاری تعطیل کی تفریق', 'ne': '- हप्ताको दिन / शनिबार / आइतबार / सार्वजनिक बिदा छुट्याइ', 'en': '- Weekday / Saturday / Sunday / Public holiday breakdown'},
  'feature3': {'tr': '- Net / Brut maas hesaplama', 'ur': '- خالص / مجموعی تنخواہ کا حساب', 'ne': '- खुद / कुल तलब गणना', 'en': '- Net / Gross salary calculation'},
  'feature4': {'tr': '- Yillik izin takibi', 'ur': '- سالانہ چھٹی کا ٹریکنگ', 'ne': '- वार्षिक बिदा ट्र्याकिङ', 'en': '- Annual leave tracking'},
  'feature5': {'tr': '- Yillara gore vergi ve asgari ucret ayarlari', 'ur': '- سالوں کے مطابق ٹیکس اور کم از کم اجرت کی ترتیبات', 'ne': '- वर्ष अनुसार कर र न्यूनतम ज्याला सेटिङ', 'en': '- Yearly tax and minimum wage settings'},
  'aboutDisclaimer': {
    'tr': 'Not: Bu uygulamadaki hesaplamalar tahmini olup yasal bir belge niteligi tasimaz. Kesin maas bilgileriniz icin isvereninize veya bordronuza basvurunuz.',
    'ur': 'نوٹ: اس ایپ کے حسابات تخمینی ہیں اور قانونی دستاویز کی حیثیت نہیں رکھتے۔ درست تنخواہ کی معلومات کے لیے اپنے آجر یا پے سلپ سے رجوع کریں۔',
    'ne': 'नोट: यस एपका गणनाहरू अनुमानित हुन् र कानुनी कागजातको हैसियत राख्दैनन्। सटीक तलब जानकारीको लागि आफ्नो रोजगारदाता वा पेस्लिपमा सम्पर्क गर्नुहोस्।',
    'en': 'Note: The calculations in this app are estimates and do not constitute a legal document. For exact salary information, please consult your employer or payslip.',
  },
  'developerLabel': {'tr': 'Gelistirici: Salih Oznal', 'ur': 'ڈیولپر: صالح اوزنال', 'ne': 'विकासकर्ता: सालिह ओज्नाल', 'en': 'Developer: Salih Oznal'},
  'lateDeduction': {'tr': 'Geç kalma kesintisi:', 'ur': 'دیر سے آنے کی کٹوتی:', 'ne': 'ढिलो आउने कटौती:', 'en': 'Late/early deduction:'},
  'sickDaysLabel': {'tr': 'Raporlu gün sayısı:', 'ur': 'بیماری کی چھٹی کے دن:', 'ne': 'बिरामी बिदाका दिन:', 'en': 'Number of sick days:'},
  'absentDaysLabel': {'tr': 'Devamsız gün sayısı:', 'ur': 'غیر حاضر دنوں کی تعداد:', 'ne': 'अनुपस्थित दिन संख्या:', 'en': 'Number of absent days:'},
  'absentDeduction': {'tr': 'Devamsızlık kesintisi:', 'ur': 'غیر حاضری کٹوتی:', 'ne': 'अनुपस्थिति कटौती:', 'en': 'Absence deduction:'},
  'unpaidLeaveDaysLabel': {'tr': 'Ücretsiz izin gün sayısı:', 'ur': 'بلا تنخواہ چھٹی کے دن:', 'ne': 'बिना तलब बिदाका दिन:', 'en': 'Number of unpaid leave days:'},
  'unpaidLeaveDeduction': {'tr': 'Ücretsiz izin kesintisi:', 'ur': 'بلا تنخواہ چھٹی کٹوتی:', 'ne': 'बिना तलब बिदा कटौती:', 'en': 'Unpaid leave deduction:'},
  'day_compOff': {'tr': 'Telafi izni kullandım', 'ur': 'میں نے تلافی چھٹی استعمال کی', 'ne': 'मैले क्षतिपूर्ति बिदा प्रयोग गरें', 'en': 'I used compensatory leave'},
  'day_compOffHours': {'tr': 'Kaç saat telafi izni kullandınız?', 'ur': 'آپ نے کتنے گھنٹے تلافی چھٹی استعمال کی؟', 'ne': 'तपाईंले कति घण्टा क्षतिपूर्ति बिदा प्रयोग गर्नुभयो?', 'en': 'How many hours of compensatory leave did you use?'},
  'day_compOffDayQuestion': {'tr': 'Hangi günün mesaisinden düşülsün?', 'ur': 'کس دن کے اضافی کام سے کاٹا جائے؟', 'ne': 'कुन दिनको ओभरटाइमबाट घटाइयोस्?', 'en': "Which day's overtime should it be deducted from?"},
  'day_compOffDay': {'tr': 'Kesinti günü', 'ur': 'کٹوتی کا دن', 'ne': 'कटौती दिन', 'en': 'Deduction day'},
  'compOffSaturday': {'tr': 'Cumartesi', 'ur': 'ہفتہ', 'ne': 'शनिबार', 'en': 'Saturday'},
  'compOffSunday': {'tr': 'Pazar', 'ur': 'اتوار', 'ne': 'आइतबार', 'en': 'Sunday'},
  'compOffChange': {'tr': 'Değiştir', 'ur': 'تبدیل کریں', 'ne': 'परिवर्तन गर्नुहोस्', 'en': 'Change'},
  'compOffDeduction': {'tr': 'Telafi izni kesintisi:', 'ur': 'تلافی چھٹی کٹوتی:', 'ne': 'क्षतिपूर्ति बिदा कटौती:', 'en': 'Compensatory leave deduction:'},
  'typeCompOff': {'tr': 'Telafi İzni', 'ur': 'تلافی چھٹی', 'ne': 'क्षतिपूर्ति बिदा', 'en': 'Compensatory Leave'},
  'day_absentHours': {'tr': 'Kaç saat işe gitmediniz?', 'ur': 'آپ کتنے گھنٹے کام پر نہیں گئے؟', 'ne': 'तपाईं कति घण्टा काममा जानुभएन?', 'en': 'How many hours were you absent?'},
};

String t(String key) {
  final lang = languageNotifier.value;
  final entry = _translations[key];
  if (entry == null) return key;
  return entry[lang] ?? entry['tr'] ?? key;
}

String t2(String key) => t(key);

List<String> monthNames() {
  return t('months').split(',');
}

TextDirection currentTextDirection() {
  return languageNotifier.value == 'ur' ? TextDirection.rtl : TextDirection.ltr;
}
